services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend

    ports:
      - "8080:8080"

    depends_on:
      - postgres
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend