spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080